# Generated by Django 3.2 on 2021-04-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='message',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion',
            field=models.CharField(choices=[('underweight', 'UNDERWEIGHT'), ('normalweight', 'NORMALWEIGHT'), ('overweight', 'OVERWEIGHT'), ('obsessed', 'OBSESSEDWEIGHT')], max_length=255),
        ),
    ]
