# Generated by Django 3.2 on 2021-05-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20210423_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmi',
            name='bmi',
        ),
    ]
